inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  Include:
    - '**/*.rb'
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'log/**/*'
    - 'ruumba/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  NewCops: enable

Layout/LineLength:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Metrics/MethodLength:
  Max: 20

