version: '3'

services:

  web:
    build: .
    ports:
      - "4567:4567"
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    depends_on:
      - mariadb
      - solr-catalog
    command: bundle exec ruby search_client.rb -o 0.0.0.0
    environment:
      DB_CONNECTION_STRING: "mysql2://ht_rights:ht_rights@mariadb/ht"
      SKIP_AUTH: "true"
    env_file:
      - .env

  test:
    build: .
    ports:
      - "4567:4567"
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    depends_on:
      - mariadb
      - solr-catalog
    command: bin/wait-for mariadb:3306 solr-catalog:9033 -- bundle exec rspec
    environment:
      DB_CONNECTION_STRING: "mysql2://ht_rights:ht_rights@mariadb/ht"
      SKIP_AUTH: "true"
    env_file:
      - .env

  solr-catalog:
    image: ghcr.io/hathitrust/catalog-solr-sample
 
  mariadb:
    image: ghcr.io/hathitrust/db-image
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1 
      MYSQL_DATABASE: ht
      MYSQL_USER: ht_rights
      MYSQL_PASSWORD: ht_rights

volumes:
  gem_cache:
