version: '3'

services:

  web:
    build: .
    ports:
      - "4567:4567"
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    command: bundle exec ruby sinatra_test.rb -o 0.0.0.0
    environment:
      DB_CONNECTION_STRING: "mysql2://ht_rights:ht_rights@mariadb/ht_rights"

  mariadb:
    image: mariadb
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1 
    volumes:
      - ./sql:docker-entrypoint-initdb.d/

volumes:
  gem_cache:
