---
name: Manual Image Build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: tag
        required: true

jobs:
  build_manual:
    runs-on: ubuntu-latest
    steps:
      - uses: hathitrust/github_actions/build@address-deprecations
        with:
          image: ghcr.io/${{ github.repository }}-unstable
          dockerfile: Dockerfile.prod
          tag: ${{ github.event.inputs.tag }}
          push_latest: false
          registry_token: ${{ github.token }}
