name: Run Tests

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  # Run tests
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up tests
        run: |
          docker-compose build
          docker-compose run web bundle install

      - name: Run rubocop
        run: docker-compose run web bundle exec standardrb

      - name: Run tests
        run: docker-compose run web bundle exec rspec

